### ISSUE TITLE
CSVReader fails with files bigger than 10 MB when constructed with std::ifstream

### ISSUE THREAD

**Issue by lamorlette-cintoo** [vincentlaucsb/csv-parser#202] opened 2022-06-13 10:00 UTC
I used to construct `CVSReader` with a `std::ifstream` as follows:

    const std::filesystem::path file_path {"foo"};
    std::ifstream input(file_path , std::ios::binary | std::ios::in);
    csv::CSVReader path_reader {input};

It is working perfectly fine with relatively small files, but it throws an exception with files bigger than 10 MB.

I found out that the same files work perfectly fine when using the other `CVSReader` constructor, taking the filename as parameter:

    const std::filesystem::path file_path {"foo"};
    csv::CSVReader path_reader {file_path.string()};

(Unfortunately I can't share with you an example because I don't own them.)

**Comment by sjoubert** [comment] 2022-09-13 14:49
Duplicate of #180

**Comment by vincentlaucsb** [comment] 2024-05-20 04:29
Closing as duplicate of #180. While this is an issue, I am curious as to why people are simply not using the default memory-mapped `CSVReader` as recommended in the README.

**Closed by vincentlaucsb** 2024-05-20 04:29 UTC
