### ISSUE TITLE
Crash on assertion failure ( Assertion failed! Line: 883 )

### ISSUE THREAD

**Issue by bangusi** [vincentlaucsb/csv-parser#90] opened 2020-04-26 23:55 UTC
on Windows
Visual Studio 2017
Library version 1.3.0

Trying to parse this file https://www.kaggle.com/austinreese/craigslist-carstrucks-data

```
Assertion failed!

Program: ...x64\Debug\Fileparse.exe
.. \csv.hpp
Line: 883

Expression: pos < size()
```

**Comment by vincentlaucsb** [comment] 2020-05-01 02:38
Thanks, I'll take a look

**Comment by vincentlaucsb** [comment] 2020-05-09 06:31
It appears this is an instance of the guessing algorithm choking. However, I'm not sure what the "fix" is since I think it's pretty well documented that you might need to manually specify the format in edge cases (like large files).

If you manually set the delimiter to a comma, then you the code below reports 539,757 rows. Kaggle says there's 539,759 unique URL values, so we're almost in agreement here.

## Example Code 
```
#include <csv.hpp>

int main(int argc, char* argv[])
{
    try {
        using namespace csv;
        CSVFormat my_format;
        my_format.delimiter(',');

        CSVReader reader("vehicles.csv", my_format);

        int i = 0;
        for (auto& row: reader) {
            i++;
        }

        std::cout << "There are " << i << " rows and " << reader.get_col_names().size() << " columns" << std::endl;
    }
    catch (std::runtime_error& err) {
        std::cout << err.what() << std::endl;
    }
}
```

## Result
> There are 539757 rows and 25 columns

**Comment by vincentlaucsb** [comment] 2020-05-09 06:37
More specifically, the guessing algorithm chokes because there's a ton of tab characters in the car descriptions. Hence, based on the relatively simple heuristic that the guessing algorithm uses (max rows * columns parsed "successfully" in the first 500kb of data), it looks like the file is tab-separated when it is not.

This is a very special case that only applies to CSV files containing lots of text with lots of tabs.

**Comment by bangusi** [comment] 2020-05-10 00:33
Didn't mean to close this because I don't think you have a fix.
Where you able to reproduce the crash? 
In your code you are not parsing the cells, just the rows that's why your are able to get to the end of the file without crashing.

**Comment by vincentlaucsb** [comment] 2020-05-11 05:51
Hi, I was able to fix the guessing algorithm, but now it's crashing due to another reason.

The problem is pretty dumb (I accessed a non-existent index) so a fix will be out soon.

**Comment by bangusi** [comment] 2020-05-11 15:36
I my case I don't think the guessing algorithm was the issue because all my tests were specifying one delimiter ( the comma ). Unless the library tries to guess regardless.

**Comment by vincentlaucsb** [comment] 2020-05-12 09:13
This is a very strange bug. At first I thought it might be the presence of Unicode characters, but most of them seem to be handled correctly. It just bugs out every 8-20k rows where you get a few dozen rows of garbage, but then the rows after that are good. Weird.

**Comment by vincentlaucsb** [comment] 2020-05-13 03:16
Update: This looks like a fun dataset so I'm now personally invested in fixing it.

When I print out the CSVRow contents the second they are generated, there's no crash and no gibberish. This is definitely some sort of memory error.

**Comment by vincentlaucsb** [comment] 2020-05-13 04:19
@bangusi I'm going to test this out more tomorrow, but I the new experimental version on `craigslist_vehicles` (https://github.com/vincentlaucsb/csv-parser/tree/craigslist_vehicles) should fix the issue. I tested it by printing out every value, and it looks fine.

**Bug:** I made the mistake of creating string_views over an `std::string` that I kept appending to.

**Comment by bangusi** [comment] 2020-05-14 01:12
@vincentlaucsb  I am still getting a crash using 1.3.2

**Comment by vincentlaucsb** [comment] 2020-05-14 01:26
Are you using the version on the experimental repo? It hasn't been merged or released yet. I managed to print out all of the values (all 1.4GB of them) without error.

**Comment by bangusi** [comment] 2020-05-14 06:35
Yes, I cloned the single-include experimental version ( CSV for C++, version 1.3.2 )
Here is the call stack
`csv_test_vs.exe!issue_debug_notification(const wchar_t * const message) Line 28
	at minkernel\crts\ucrt\src\appcrt\internal\report_runtime_error.cpp(28)
csv_test_vs.exe!__acrt_report_runtime_error(const wchar_t * message) Line 154
	at minkernel\crts\ucrt\src\appcrt\internal\report_runtime_error.cpp(154)
csv_test_vs.exe!abort() Line 61
	at minkernel\crts\ucrt\src\appcrt\startup\abort.cpp(61)
csv_test_vs.exe!common_assert_to_stderr_direct(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) Line 161
	at minkernel\crts\ucrt\src\appcrt\startup\assert.cpp(161)
csv_test_vs.exe!common_assert_to_stderr<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) Line 179
	at minkernel\crts\ucrt\src\appcrt\startup\assert.cpp(179)
csv_test_vs.exe!common_assert<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number, void * const return_address) Line 420
	at minkernel\crts\ucrt\src\appcrt\startup\assert.cpp(420)
csv_test_vs.exe!_wassert(const wchar_t * expression, const wchar_t * file_name, unsigned int line_number) Line 444
	at minkernel\crts\ucrt\src\appcrt\startup\assert.cpp(444)
csv_test_vs.exe!nonstd::sv_lite::basic_string_view<char,std::char_traits<char> >::data_at(unsigned __int64 pos) Line 882
	at \csv.hpp(882)
csv_test_vs.exe!nonstd::sv_lite::basic_string_view<char,std::char_traits<char> >::operator[](unsigned __int64 pos) Line 543
	at \csv.hpp(543)
csv_test_vs.exe!csv::internals::parse(const csv::internals::ParseData & data) Line 5110
	at \csv.hpp(5110)
csv_test_vs.exe!csv::CSVReader::feed(nonstd::sv_lite::basic_string_view<char,std::char_traits<char> > in) Line 4850
	at \csv.hpp(4850)
csv_test_vs.exe!csv::CSVReader::feed(std::pair<std::unique_ptr<char [0],std::default_delete<char [0]> >,unsigned __int64> && buff) Line 4829
	at \csv.hpp(4829)
csv_test_vs.exe!csv::CSVReader::read_csv_worker() Line 4898
	at \csv.hpp(4898)
[External Code]
csv_test_vs.exe!invoke_thread_procedure(unsigned int(*)(void *) procedure, void * const context) Line 92
	at minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(92)
csv_test_vs.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115
	at minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(115)`

**Comment by vincentlaucsb** [comment] 2020-05-16 02:33
Can you see if this appears with 1.3.3, and if so, can you have the program print out the line number as well as the value of the fields?

I was able to successfully print out every field using 1.3.3 on:
* C++11 on Windows 10 w/ Visual Studio 2019
* C++17 on Windows 10 w/ Visual Studio 2019
* C++17 on Ubuntu with g++-8

**Comment by bangusi** [comment] 2020-05-16 08:41
Confirmed. The issue is fixed.

**Closed** 2020-05-16 08:41 UTC
Labels: bug

**Comment by bangusi** [comment] 2020-05-22 14:39
@vincentlaucsb 
Hi Vincent

When you have a chance try to parse this file.

https://www.kaggle.com/datasnaek/youtube-new?select=CAvideos.csv

Apparently the file should have 24,427 rows but I am getting 40,880.
The file has lots of UNICODE characters, just wondering if that is causing problems.

**Comment by vincentlaucsb** [comment] 2020-05-23 04:16
@bangusi 

Excel shows 40882 rows (40881 if you exclude the header).

![image](https://user-images.githubusercontent.com/18455475/82721300-de6a4c80-9c70-11ea-8081-79d996b7a98f.png)

I skimmed through the rows in Excel and nothing looks out of sync, so I think around 40880 is an accurate count. I know Kaggle says 24427 unique video ids, but I did a search (in Excel) and it looks like some video IDs appear multiple times.

However, it is crashing for me so I will take a look. Feel free to create a new ticket for the file if I don't remember to, since this suggests there is a bug in the parser.

**Comment by bangusi** [comment] 2020-05-23 17:24
I had tested with Excel too and the row count did not match with what the web site claims to be that's why I could not tell whether it was the library or a malformed csv.
That said I did not experience a crash and the library seems to agree with Excel
