### ISSUE TITLE
csv::set_decimal_places does not round decimals to width

### ISSUE THREAD

**Issue by telmo-carmo** [vincentlaucsb/csv-parser#182] opened 2021-08-27 11:27 UTC
csv::set_decimal_places(2);
writer << std::make_tuple(-1.043, 2.126, "Three");  // out =>  -1.04;2.12;Three

**Comment by vincentlaucsb** [comment] 2024-05-20 04:07
Closing as this is the intended behavior. It is the user's responsibility to call `std::round()` on CSV writer inputs. I do not believe all users should be saddled with the cost of calling `std::round` on all floating point inputs.

**Closed** 2024-05-20 04:08 UTC
